[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]] # R
repo = 'jalvesaq/Nvim-R'

[[plugins]] # 補完
repo = 'Shougo/neocomplete.vim'

[[plugins]] # j,kによる移動を爆速に
repo = 'rhysd/accelerated-jk'
