#!/bin/sh
ln -sf ~/dotfiles/.latexmkrc ~/.latexmkrc
ln -sf ~/dotfiles/.vimrc ~/.vimrc
ln -sf ~/dotfiles/.zpreztorc ~/.zpreztorc
ln -sf ~/dotfiles/.zshrc ~/.zshrc
ln -sf ~/dotfiles/.zlogin ~/.zlogin
ln -sf ~/dotfiles/.zlogout ~/.zlogout
ln -sf ~/dotfiles/.zprofile ~/.zprofile
ln -sf ~/dotfiles/.zshenv ~/.zshenv
ln -sf ~/dotfiles/.tmux.conf ~/.tmux.conf
ln -sf ~/dotfiles/.gitignore_global ~/.gitignore_global
ln -sf ~/dotfiles/gitconfig ~/.gitconfig
ln -sf ~/dotfiles/.hyper.js ~/.hyper.js
ln -sf ~/dotfiles/karabiner ~/.config/
if [ ! -L ~/.zprezto -a -d ~/dotfiles/prezto ]; then
    ln -s ~/dotfiles/prezto ~/.zprezto
fi
/usr/local/bin/brew bundle --file=~/dotfiles/Brewfile
pyenv install 3.6.0
pip3 --no-cache-dir install -I neovim
